apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  labels:
    app: spark
    component: master
    {{- with .Values.labels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.master.replicas }}
  selector:
    matchLabels:
      app: spark
      component: master
  template:
    metadata:
      labels:
        app: spark
        component: master
    spec:
      containers:
        - name: spark-master
          image: "{{ .Values.master.image.repository }}:{{ .Values.master.image.tag }}"
          imagePullPolicy: {{ .Values.master.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.master.service.port }}
          resources:
            limits:
              cpu: {{ .Values.master.resources.limits.cpu }}
              memory: {{ .Values.master.resources.limits.memory }}
            requests:
              cpu: {{ .Values.master.resources.requests.cpu }}
              memory: {{ .Values.master.resources.requests.memory }}
          volumeMounts:
            - name: spark-storage
              mountPath: {{ .Values.persistence.mountPath }}
      volumes:
        - name: spark-storage
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}
                            {{ .Values.persistence.existingClaim }}
                        {{- else if .Values.persistence.shared }}
                            {{ .Values.persistence.sharedClaim }}
                        {{- else }}
                            {{ .Values.persistence.masterClaim }}
                        {{- end }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}


